name: eog
adopt-info: eog
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog
  /usr/share/eog:
    bind: $SNAP/usr/share/eog

slots:
  # for GtkApplication registration
  eog:
    interface: dbus
    bus: session
    name: org.gnome.eog

apps:
  eog:
    common-id: org.gnome.eog.desktop
    command: usr/bin/eog
    extensions: [gnome-3-38]
    plugs:
      - home
      - gsettings
      - network
      - mount-observe
      - removable-media
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/eog:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog
      GI_TYPELIB_PATH: $SNAP/usr/lib/eog/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages
      
parts:

  eog:
    #after: [ libportal ]
    source: https://gitlab.gnome.org/GNOME/eog.git
    source-type: git
    source-tag: '40.2'
    parse-info: [usr/share/metainfo/eog.appdata.xml]
    plugin: meson
    meson-parameters: [--prefix=/snap/eog/current/usr, -Dintrospection=true, -Dlibportal=false]
    meson-version: 0.58.1
    organize:
      snap/eog/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.eog$|=${SNAP}/meta/gui/org.gnome.eog.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.eog.desktop.in.in
      sed -i.bak -e 's|media: media,|media: media, symlink_media: false,|g' $SNAPCRAFT_PART_SRC/help/meson.build
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/scalable/apps/org.gnome.eog.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_BUILD/data/org.gnome.eog.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libexempi-dev
      - libexif-dev
      - libjpeg-dev
      - liblcms2-dev
      - zlib1g-dev
    build-environment:
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS

  libraries:
    after: [eog]
    plugin: nil
    stage-packages:
      - libexif12
      - libexempi8
    prime:
      - "usr/lib/*/libexif*"
      - "usr/lib/*/libexempi*"

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [libraries]
    plugin: nil
    build-snaps: [core20, gtk-common-themes, gnome-3-38-2004]
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
